### PR TITLE
fixed build with boost1.67+

### PR DESCRIPTION
**Pull request by arcmags**
Fix building with boost 1.67.
See issue #53

### CODE REVIEW

**Comment by cryptochangements34** [comment]
This conflicts with and will likely be superseded by #56

**Comment by arcmags** [comment]
Dang, too late for the bounty.  #56 looks good, though.  Keep up the good work!

**Comment by thaerkh** [comment]
@arcmags can you provide us an MSR address? we'd like to reward you since this PR preceded the larger one that contained it

**Comment by arcmags** [comment]
Awesome, sure, thanks!
5mHzG8PAj8DQFvidGxYtj7WgD8Jt7Z1Lqj3QaaxFo9SKSCssbRdJ8EpY11SNc6oaZ99RDkw6VV9Yj8hzYevPBZpo6BTBmxU

**Pull request closed without merging**
